import { Poppins } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from "./lib/registry";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "True Connect",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StyledComponentsRegistry>
        <body className={poppins.className}>{children}</body>
      </StyledComponentsRegistry>
    </html>
  );
}
